/* SPDX-License-Identifier: BSD-3-Clause
 * Copyright (c) 2026 DroidVM contributors.
 * Separate virtio-media function in the VioGPU package: never GPU controlq.
 */
#include "video.h"
static const GUID VvInterface=VV_INTERFACE_GUID_INIT;

/* Register the KMDF media companion without changing the display miniport. */
NTSTATUS DriverEntry(PDRIVER_OBJECT object, PUNICODE_STRING registry)
{
    WDF_DRIVER_CONFIG config;
    WDF_DRIVER_CONFIG_INIT(&config,VvAdd);
    return WdfDriverCreate(object,registry,WDF_NO_OBJECT_ATTRIBUTES,&config,WDF_NO_HANDLE);
}

/* Create one exclusive, administrator-only bring-up endpoint per media function. */
NTSTATUS VvAdd(WDFDRIVER driver, PWDFDEVICE_INIT init)
{
    WDF_PNPPOWER_EVENT_CALLBACKS pnp;
    WDF_FILEOBJECT_CONFIG file;
    WDF_OBJECT_ATTRIBUTES attrs;
    WDF_INTERRUPT_CONFIG irq;
    WDF_IO_QUEUE_CONFIG queue;
    WDFDEVICE device;
    VV_DEVICE *d;
    NTSTATUS status;
    DECLARE_CONST_UNICODE_STRING(sddl,L"D:P(A;;GA;;;SY)(A;;GA;;;BA)");
    UNREFERENCED_PARAMETER(driver);
    WdfDeviceInitSetExclusive(init,TRUE);
    WdfDeviceInitSetCharacteristics(init,FILE_AUTOGENERATED_DEVICE_NAME|FILE_DEVICE_SECURE_OPEN,FALSE);
    WdfDeviceInitSetIoType(init,WdfDeviceIoBuffered);
    status=WdfDeviceInitAssignSDDLString(init,&sddl);
    if (!NT_SUCCESS(status)) return status;
    WDF_FILEOBJECT_CONFIG_INIT(&file,WDF_NO_EVENT_CALLBACK,WDF_NO_EVENT_CALLBACK,VvCleanup);
    WDF_OBJECT_ATTRIBUTES_INIT(&attrs);
    attrs.ExecutionLevel=WdfExecutionLevelPassive;
    WdfDeviceInitSetFileObjectConfig(init,&file,&attrs);
    WDF_PNPPOWER_EVENT_CALLBACKS_INIT(&pnp);
    pnp.EvtDevicePrepareHardware=VvPrepare; pnp.EvtDeviceReleaseHardware=VvRelease;
    pnp.EvtDeviceD0Entry=VvD0Entry; pnp.EvtDeviceD0Exit=VvD0Exit;
    WdfDeviceInitSetPnpPowerEventCallbacks(init,&pnp);
    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&attrs,VV_DEVICE);
    attrs.SynchronizationScope=WdfSynchronizationScopeNone;
    status=WdfDeviceCreate(&init,&attrs,&device);
    if (!NT_SUCCESS(status)) return status;
    d=VvDevice(device); d->device=device;
    KeInitializeEvent(&d->command_done,NotificationEvent,FALSE);
    WDF_OBJECT_ATTRIBUTES_INIT(&attrs); attrs.ParentObject=device;
    status=WdfSpinLockCreate(&attrs,&d->lock);
    if (!NT_SUCCESS(status)) return status;
    status=WdfWaitLockCreate(&attrs,&d->gate);
    if (!NT_SUCCESS(status)) return status;
    WDF_INTERRUPT_CONFIG_INIT(&irq,VvIsr,VvDpc);
    irq.AutomaticSerialization=FALSE;
    irq.EvtInterruptEnable=VvInterruptEnable;
    irq.EvtInterruptDisable=VvInterruptDisable;
    status=WdfInterruptCreate(device,&irq,WDF_NO_OBJECT_ATTRIBUTES,&d->interrupt);
    if (!NT_SUCCESS(status)) return status;
    status=WdfDeviceCreateDeviceInterface(device,&VvInterface,NULL);
    if (!NT_SUCCESS(status)) return status;
    WDF_IO_QUEUE_CONFIG_INIT_DEFAULT_QUEUE(&queue,WdfIoQueueDispatchSequential);
    queue.EvtIoDeviceControl=VvControl;
    WDF_OBJECT_ATTRIBUTES_INIT(&attrs);
    attrs.ExecutionLevel=WdfExecutionLevelPassive;
    return WdfIoQueueCreate(device,&queue,&attrs,WDF_NO_HANDLE);
}

/* Refuse translated DMA addresses: USERPTR SG currently carries actual guest PA. */
NTSTATUS VvPrepare(WDFDEVICE device, WDFCMRESLIST raw, WDFCMRESLIST translated)
{
    VV_DEVICE *d=VvDevice(device);
    NTSTATUS status;
    UNREFERENCED_PARAMETER(raw);
    status=VirtIOWdfInitialize(&d->virtio,device,translated,NULL,VV_TAG);
    if (!NT_SUCCESS(status)) return status;
    d->initialized=TRUE;
    if (d->virtio.IsIoMmuActive) return STATUS_NOT_SUPPORTED;
    if (!(VirtIOWdfGetDeviceFeatures(&d->virtio)&(1ull<<VIRTIO_F_VERSION_1)))
        return STATUS_NOT_SUPPORTED;
    return STATUS_SUCCESS;
}

/* Populate an event descriptor; call with the queue lock after queue creation. */
static int VvPostEvent(VV_DEVICE *d, ULONG slot)
{
    struct scatterlist sg;
    sg.physAddr.QuadPart=d->event_pa.QuadPart+(LONGLONG)slot*VV_EVENT_BYTES;
    sg.length=VV_EVENT_BYTES;
    return virtqueue_add_buf(d->queues[VV_QUEUE_EVENT],&sg,0,1,
                             (PUCHAR)d->event_memory+slot*VV_EVENT_BYTES,NULL,0);
}

/* Prepost the event ring before DRIVER_OK, then enable ordinary PCI interrupts. */
NTSTATUS VvD0Entry(WDFDEVICE device, WDF_POWER_DEVICE_STATE previous)
{
    VV_DEVICE *d=VvDevice(device);
    VIRTIO_WDF_QUEUE_PARAM params[2];
    NTSTATUS status;
    ULONG i;
    UNREFERENCED_PARAMETER(previous);
    WdfWaitLockAcquire(d->gate,NULL);
    InterlockedExchange(&d->faulted,0);
    d->read_at=0; d->event_count=0; d->pending=FALSE; d->have_session=FALSE;
    params[0].Interrupt=d->interrupt; params[1].Interrupt=d->interrupt;
    status=VirtIOWdfInitQueues(&d->virtio,2,d->queues,params);
    if (!NT_SUCCESS(status)) goto out;
    d->queues_created=TRUE;
    d->command_memory=VirtIOWdfDeviceAllocDmaMemory(&d->virtio.VIODevice,2*VV_COMMAND_BYTES,VV_TAG);
    d->event_memory=VirtIOWdfDeviceAllocDmaMemory(&d->virtio.VIODevice,VV_EVENT_SLOTS*VV_EVENT_BYTES,VV_TAG);
    if (!d->command_memory || !d->event_memory) { status=STATUS_INSUFFICIENT_RESOURCES; goto out; }
    d->command_pa=VirtIOWdfDeviceGetPhysicalAddress(&d->virtio.VIODevice,d->command_memory);
    d->event_pa=VirtIOWdfDeviceGetPhysicalAddress(&d->virtio.VIODevice,d->event_memory);
    RtlZeroMemory(d->event_memory,VV_EVENT_SLOTS*VV_EVENT_BYTES);
    for (i=0;i<VV_EVENT_SLOTS;++i) {
        if (VvPostEvent(d,i)<0) {
            if (!i) { status=STATUS_INSUFFICIENT_RESOURCES; goto out; }
            break; /* The device may offer fewer descriptors than our local upper bound. */
        }
    }
    VirtIOWdfDeviceGet(&d->virtio,0,&d->config,sizeof(d->config));
    InterlockedExchange(&d->online,1);
    VirtIOWdfSetDriverOK(&d->virtio);
    virtqueue_kick(d->queues[VV_QUEUE_EVENT]);
    status=STATUS_SUCCESS;
out:
    if (!NT_SUCCESS(status)) {
        VirtIOWdfSetDriverFailed(&d->virtio);
        if (d->queues_created) { VirtIOWdfDestroyQueues(&d->virtio); d->queues_created=FALSE; }
        VirtIOWdfDeviceFreeDmaMemoryByTag(&d->virtio.VIODevice,VV_TAG);
        d->command_memory=NULL; d->event_memory=NULL;
    }
    WdfWaitLockRelease(d->gate);
    return status;
}

/* Quiesce DPCs, reset the device, then release retained descriptors and video data. */
NTSTATUS VvD0Exit(WDFDEVICE device, WDF_POWER_DEVICE_STATE target)
{
    VV_DEVICE *d=VvDevice(device);
    NTSTATUS status=STATUS_SUCCESS;
    UNREFERENCED_PARAMETER(target);
    WdfWaitLockAcquire(d->gate,NULL);
    WdfSpinLockAcquire(d->lock);
    InterlockedExchange(&d->online,0);
    WdfSpinLockRelease(d->lock);
    WdfInterruptFlushQueuedDpcs(d->interrupt);
    if (d->queues_created) {
        status=VirtIOWdfDestroyQueues(&d->virtio);
        if (NT_SUCCESS(status)) d->queues_created=FALSE;
    }
    if (NT_SUCCESS(status)) {
        d->have_session=FALSE; d->pending=FALSE;
        VvFreeBuffers(d);
        VirtIOWdfDeviceFreeDmaMemoryByTag(&d->virtio.VIODevice,VV_TAG);
        d->command_memory=NULL; d->event_memory=NULL;
    }
    WdfWaitLockRelease(d->gate);
    return status;
}

/* Release the shared VirtIO library after D0 has reset the media function. */
NTSTATUS VvRelease(WDFDEVICE device, WDFCMRESLIST translated)
{
    VV_DEVICE *d=VvDevice(device);
    UNREFERENCED_PARAMETER(translated);
    if (!d->initialized) return STATUS_SUCCESS;
    d->initialized=FALSE;
    return VirtIOWdfShutdown(&d->virtio);
}

/* Enable notifications after KMDF has connected the interrupt. */
NTSTATUS VvInterruptEnable(WDFINTERRUPT interrupt, WDFDEVICE device)
{
    VV_DEVICE *d=VvDevice(device);
    BOOLEAN empty;
    UNREFERENCED_PARAMETER(interrupt);
    if (!d->online) return STATUS_SUCCESS;
    empty=(BOOLEAN)virtqueue_enable_cb(d->queues[0]);
    empty=(BOOLEAN)(virtqueue_enable_cb(d->queues[1]) && empty);
    virtqueue_kick(d->queues[1]);
    if (!empty) WdfInterruptQueueDpcForIsr(d->interrupt);
    return STATUS_SUCCESS;
}

/* Disable notifications before KMDF disconnects the interrupt. */
NTSTATUS VvInterruptDisable(WDFINTERRUPT interrupt, WDFDEVICE device)
{
    VV_DEVICE *d=VvDevice(device);
    UNREFERENCED_PARAMETER(interrupt);
    if (d->queues_created) {
        virtqueue_disable_cb(d->queues[0]);
        virtqueue_disable_cb(d->queues[1]);
    }
    return STATUS_SUCCESS;
}

/* Acknowledge INTx or accept the MSI routed to these two media queues. */
BOOLEAN VvIsr(WDFINTERRUPT interrupt, ULONG message)
{
    VV_DEVICE *d=VvDevice(WdfInterruptGetDevice(interrupt));
    UNREFERENCED_PARAMETER(message);
    if (!d->online) return FALSE;
    if (!d->virtio.nMSIInterrupts && !(VirtIOWdfGetISRStatus(&d->virtio)&1)) return FALSE;
    WdfInterruptQueueDpcForIsr(interrupt);
    return TRUE;
}

/* Recycle event descriptors immediately; preserve only sanitized completion metadata. */
VOID VvDpc(WDFINTERRUPT interrupt, WDFOBJECT associated)
{
    VV_DEVICE *d=VvDevice(WdfInterruptGetDevice(interrupt));
    PVOID token;
    unsigned int used;
    ULONG budget=VV_EVENT_RING;
    UNREFERENCED_PARAMETER(associated);
    WdfSpinLockAcquire(d->lock);
    if (!d->online) goto out;
    token=virtqueue_get_buf(d->queues[VV_QUEUE_COMMAND],&used);
    if (token) {
        if (token!=d->command_memory || !d->pending) InterlockedExchange(&d->faulted,1);
        else { d->command_used=used; d->pending=FALSE; KeSetEvent(&d->command_done,IO_NO_INCREMENT,FALSE); }
    }
    /* Split-ring notification suppression is not enabled; every completion interrupts. */
    while (budget-- && (token=virtqueue_get_buf(d->queues[VV_QUEUE_EVENT],&used))!=NULL) {
        SIZE_T offset=(SIZE_T)((ULONG_PTR)token-(ULONG_PTR)d->event_memory);
        VV_EVENT event;
        if (offset>=VV_EVENT_SLOTS*VV_EVENT_BYTES || offset%VV_EVENT_BYTES) {
            InterlockedExchange(&d->faulted,1); break;
        }
        if (!vv_parse_event(token,used,&event) || d->event_count==VV_EVENT_RING)
            InterlockedExchange(&d->faulted,1);
        else {
            d->events[(d->read_at+d->event_count)%VV_EVENT_RING]=event;
            ++d->event_count;
        }
        if (VvPostEvent(d,(ULONG)(offset/VV_EVENT_BYTES))<0) InterlockedExchange(&d->faulted,1);
    }
    /* Exhaustion is fatal, not a silently dropped completion or an unbounded DPC. */
    if (budget==MAXULONG) InterlockedExchange(&d->faulted,1);
    virtqueue_kick(d->queues[VV_QUEUE_EVENT]);
out:
    WdfSpinLockRelease(d->lock);
}

/* The caller holds gate, not a spinlock; timeout never releases DMA-visible memory. */
NTSTATUS VvTransact(VV_DEVICE *d, const void *command, ULONG command_size,
                    void *reply, ULONG reply_capacity, ULONG *reply_size)
{
    struct scatterlist sg[2];
    LARGE_INTEGER timeout;
    NTSTATUS status;
    if (!command || !reply || !reply_size || command_size>VV_COMMAND_BYTES ||
        reply_capacity>VV_COMMAND_BYTES || reply_capacity<sizeof(VV_RESPONSE)) return STATUS_INVALID_PARAMETER;
    WdfSpinLockAcquire(d->lock);
    if (!d->online || d->faulted || d->pending) {
        WdfSpinLockRelease(d->lock); return STATUS_DEVICE_NOT_READY;
    }
    RtlZeroMemory(d->command_memory,2*VV_COMMAND_BYTES);
    RtlCopyMemory(d->command_memory,command,command_size);
    sg[0].physAddr=d->command_pa; sg[0].length=command_size;
    sg[1].physAddr.QuadPart=d->command_pa.QuadPart+VV_COMMAND_BYTES;
    sg[1].length=reply_capacity;
    KeClearEvent(&d->command_done); d->pending=TRUE; d->command_used=0;
    if (virtqueue_add_buf(d->queues[0],sg,1,1,d->command_memory,NULL,0)<0) {
        d->pending=FALSE; WdfSpinLockRelease(d->lock); return STATUS_DEVICE_BUSY;
    }
    virtqueue_kick(d->queues[0]);
    WdfSpinLockRelease(d->lock);
    timeout.QuadPart=-15ll*1000*1000*10; /* Longer than the host's 10-second start bound. */
    status=KeWaitForSingleObject(&d->command_done,Executive,KernelMode,FALSE,&timeout);
    WdfSpinLockAcquire(d->lock);
    if (status!=STATUS_SUCCESS || d->faulted || d->command_used<sizeof(VV_RESPONSE) ||
        d->command_used>reply_capacity) {
        InterlockedExchange(&d->faulted,1);
        status=(status==STATUS_TIMEOUT)?STATUS_IO_TIMEOUT:STATUS_DEVICE_PROTOCOL_ERROR;
    } else {
        RtlCopyMemory(reply,(PUCHAR)d->command_memory+VV_COMMAND_BYTES,d->command_used);
        *reply_size=d->command_used;
    }
    WdfSpinLockRelease(d->lock);
    return status;
}
