/*
 * pvmpower - Gunyah protected-VM power driver (PSCI shutdown / reboot bridge).
 *
 * crosvm on this platform exposes no ACPI power or reset registers (the ACPI
 * tables are generated by edk2 from the FDT), so Windows' native S5 path has
 * nothing to poke and the VM hangs at the very end of shutdown until the host
 * kills it (DRIVER_POWER_STATE_FAILURE when power IRPs then time out). The
 * platform DOES implement PSCI via HVC: Linux/edk2 power off and reboot
 * through it, Gunyah forwards SYSTEM_OFF / SYSTEM_RESET to crosvm, crosvm
 * exits with a distinct code (reset = 32) and the DroidVM daemon relaunches
 * the VM on reset. This driver bridges Windows onto that path:
 *
 *  - It binds to a root-enumerated device (ROOT\PVMPOWER, created by the
 *    installer) so it sits in the PnP tree and receives system power IRPs.
 *  - IRP_MJ_POWER preprocess (KMDF does not surface raw power IRPs): when the
 *    S5 SET_POWER IRP (SystemState == PowerSystemShutdown) arrives, read its
 *    ShutdownType (POWER_ACTION) - the documented reboot-vs-poweroff
 *    discriminator - and IMMEDIATELY issue PSCI SYSTEM_RESET (0x84000009) for
 *    PowerActionShutdownReset, else SYSTEM_OFF (0x84000008).
 *  - IRP_MJ_SHUTDOWN preprocess + IoRegisterLastChanceShutdownNotification:
 *    arms a fallback timer only. Measured on the device (breadcrumb run,
 *    2026-07-02): the shutdown sequence is normal notifications -> FS flush ->
 *    LAST-CHANCE -> and only THEN the S5 device power IRPs. Firing PSCI at
 *    last-chance therefore killed the VM before any S5 IRP (and its
 *    ShutdownType) could ever be seen - reboot always degraded to power-off.
 *    Firing at the S5 IRP is strictly later, so it is at least as safe; the
 *    last-chance timer (PSCI SYSTEM_OFF after 10s) only fires if this
 *    platform ever fails to deliver an S5 IRP, restoring the old behavior.
 *
 * This package is staged only on the DroidVM/Gunyah image. It therefore
 * directly bridges the root-enumerated power device to the platform PSCI
 * conduit; no auxiliary marker device is required.
 *
 * Copyright (c) 2026
 * SPDX-License-Identifier: BSD-2-Clause-Patent
 */

#include <ntddk.h>
#include <wdf.h>

/* PSCI function IDs (SMC64), conduit "hvc" on this platform. Stub in
 * pvmpower_psci.asm places fn/args in x0-x3 per the C ABI and executes HVC #0. */
extern unsigned long long PsciHvcCall(unsigned long long Fn,
                                      unsigned long long Arg1,
                                      unsigned long long Arg2,
                                      unsigned long long Arg3);
#define PSCI_SYSTEM_OFF   0x84000008ULL
#define PSCI_SYSTEM_RESET 0x84000009ULL

DRIVER_INITIALIZE DriverEntry;
EVT_WDF_DRIVER_DEVICE_ADD PvmPowerEvtDeviceAdd;
EVT_WDFDEVICE_WDM_IRP_PREPROCESS PvmPowerPowerIrpPreprocess;
EVT_WDFDEVICE_WDM_IRP_PREPROCESS PvmPowerShutdownIrp;

/* ShutdownType (POWER_ACTION) captured from the S5 system power IRP; kept for
 * the fallback path. PowerActionNone until an S5 IRP is seen -> SYSTEM_OFF. */
static volatile LONG g_ShutdownAction = PowerActionNone;

/* Fallback: armed at last-chance shutdown; fires PSCI SYSTEM_OFF if no S5
 * power IRP shows up to do the job properly (see header comment). */
static KTIMER g_FallbackTimer;
static KDPC g_FallbackDpc;
#define PVMPOWER_FALLBACK_TIMEOUT_SEC 10

/* Ensure PSCI is issued at most once (S5 path vs fallback timer race). */
static volatile LONG g_PsciFired = 0;

/*
 * Issue PSCI at most once, picking RESET vs OFF from the given action. Any
 * IRQL (the HVC stub is a single instruction and does not return on success).
 */
static VOID PvmPowerDoPsci(POWER_ACTION action, PCSTR origin)
{
    ULONGLONG fn = (action == PowerActionShutdownReset) ? PSCI_SYSTEM_RESET : PSCI_SYSTEM_OFF;

    if (InterlockedExchange(&g_PsciFired, 1) != 0)
    {
        return;
    }
    DbgPrintEx(DPFLTR_DEFAULT_ID,
               DPFLTR_INFO_LEVEL,
               "pvmpower: %s, action=%d -> PSCI %s\n",
               origin,
               action,
               fn == PSCI_SYSTEM_RESET ? "SYSTEM_RESET" : "SYSTEM_OFF");
    (void)PsciHvcCall(fn, 0, 0, 0);
    /* Should not return (VM reset or powered off). */
    DbgPrintEx(DPFLTR_DEFAULT_ID, DPFLTR_ERROR_LEVEL, "pvmpower: PSCI call returned!\n");
}

static KDEFERRED_ROUTINE PvmPowerFallbackDpc;
_Use_decl_annotations_ static VOID PvmPowerFallbackDpc(PKDPC Dpc, PVOID Context, PVOID Arg1, PVOID Arg2)
{
    UNREFERENCED_PARAMETER(Dpc);
    UNREFERENCED_PARAMETER(Context);
    UNREFERENCED_PARAMETER(Arg1);
    UNREFERENCED_PARAMETER(Arg2);
    /* No S5 power IRP arrived after last-chance shutdown: power off like the
     * original behavior so the VM never hangs at the dead HalReturnToFirmware. */
    PvmPowerDoPsci((POWER_ACTION)InterlockedCompareExchange(&g_ShutdownAction, 0, 0), "fallback timer");
}

/*
 * IRP_MJ_POWER preprocess. For the S5 SET_POWER IRP this is where the VM
 * actually powers off / reboots: the IRP carries the authoritative
 * ShutdownType, and by this point last-chance shutdown has already run (see
 * header comment). Everything else is peeked and passed straight back. May
 * run up to DISPATCH_LEVEL, so only the cached platform flag is used.
 */
NTSTATUS
PvmPowerPowerIrpPreprocess(_In_ WDFDEVICE Device, _Inout_ PIRP Irp)
{
    PIO_STACK_LOCATION irpStack = IoGetCurrentIrpStackLocation(Irp);

    if (irpStack->Parameters.Power.Type == SystemPowerState &&
        (irpStack->MinorFunction == IRP_MN_SET_POWER || irpStack->MinorFunction == IRP_MN_QUERY_POWER))
    {
        if (irpStack->Parameters.Power.State.SystemState == PowerSystemShutdown)
        {
            DbgPrintEx(DPFLTR_DEFAULT_ID,
                       DPFLTR_INFO_LEVEL,
                       "pvmpower: S5 power IRP (%s), ShutdownType=%d (%s)\n",
                       irpStack->MinorFunction == IRP_MN_SET_POWER ? "set" : "query",
                       irpStack->Parameters.Power.ShutdownType,
                       irpStack->Parameters.Power.ShutdownType == PowerActionShutdownReset ? "reboot" : "power-off");
            if (irpStack->MinorFunction == IRP_MN_SET_POWER)
            {
                InterlockedExchange(&g_ShutdownAction, (LONG)irpStack->Parameters.Power.ShutdownType);
                PvmPowerDoPsci(irpStack->Parameters.Power.ShutdownType, "S5 set-power IRP");
                /* Only reached if PSCI failed; fall through to normal handling. */
            }
        }
    }

    return WdfDeviceWdmDispatchPreprocessedIrp(Device, Irp);
}

/*
 * Last-chance shutdown handler (IRP_MJ_SHUTDOWN arrives here only because
 * PvmPowerEvtDeviceAdd registered for last-chance notification). Runs at
 * PASSIVE_LEVEL, BEFORE the S5 device power IRPs (measured on the device) -
 * so no PSCI here: probe the platform (PASSIVE work the S5 path cannot do)
 * and arm the no-S5-IRP fallback timer.
 */
NTSTATUS
PvmPowerShutdownIrp(_In_ WDFDEVICE Device, _Inout_ PIRP Irp)
{
    UNREFERENCED_PARAMETER(Device);

    LARGE_INTEGER due;
    due.QuadPart = -(LONGLONG)PVMPOWER_FALLBACK_TIMEOUT_SEC * 10 * 1000 * 1000; /* relative, 100ns */
    DbgPrintEx(DPFLTR_DEFAULT_ID,
               DPFLTR_INFO_LEVEL,
               "pvmpower: last-chance shutdown - waiting for the S5 power IRP (fallback in %us)\n",
               PVMPOWER_FALLBACK_TIMEOUT_SEC);
    (void)KeSetTimer(&g_FallbackTimer, due, &g_FallbackDpc);

    Irp->IoStatus.Status = STATUS_SUCCESS;
    Irp->IoStatus.Information = 0;
    IoCompleteRequest(Irp, IO_NO_INCREMENT);
    return STATUS_SUCCESS;
}

NTSTATUS
PvmPowerEvtDeviceAdd(_In_ WDFDRIVER Driver, _Inout_ PWDFDEVICE_INIT DeviceInit)
{
    NTSTATUS status;
    WDFDEVICE device;

    UNREFERENCED_PARAMETER(Driver);

    KeInitializeTimer(&g_FallbackTimer);
    KeInitializeDpc(&g_FallbackDpc, PvmPowerFallbackDpc, NULL);

    /* KMDF surfaces neither raw power IRPs nor IRP_MJ_SHUTDOWN; take both as
     * WDM preprocess callbacks. */
    status = WdfDeviceInitAssignWdmIrpPreprocessCallback(DeviceInit, PvmPowerPowerIrpPreprocess, IRP_MJ_POWER, NULL, 0);
    if (!NT_SUCCESS(status))
    {
        DbgPrintEx(DPFLTR_DEFAULT_ID,
                   DPFLTR_ERROR_LEVEL,
                   "pvmpower: assign IRP_MJ_POWER preprocess failed 0x%x\n",
                   status);
        return status;
    }

    status = WdfDeviceInitAssignWdmIrpPreprocessCallback(DeviceInit, PvmPowerShutdownIrp, IRP_MJ_SHUTDOWN, NULL, 0);
    if (!NT_SUCCESS(status))
    {
        DbgPrintEx(DPFLTR_DEFAULT_ID,
                   DPFLTR_ERROR_LEVEL,
                   "pvmpower: assign IRP_MJ_SHUTDOWN preprocess failed 0x%x\n",
                   status);
        return status;
    }

    status = WdfDeviceCreate(&DeviceInit, WDF_NO_OBJECT_ATTRIBUTES, &device);
    if (!NT_SUCCESS(status))
    {
        DbgPrintEx(DPFLTR_DEFAULT_ID, DPFLTR_ERROR_LEVEL, "pvmpower: WdfDeviceCreate failed 0x%x\n", status);
        return status;
    }

    /* Fire PvmPowerShutdownIrp at the very end of system shutdown. */
    status = IoRegisterLastChanceShutdownNotification(WdfDeviceWdmGetDeviceObject(device));
    if (!NT_SUCCESS(status))
    {
        DbgPrintEx(DPFLTR_DEFAULT_ID,
                   DPFLTR_ERROR_LEVEL,
                   "pvmpower: IoRegisterLastChanceShutdownNotification failed 0x%x\n",
                   status);
        return status;
    }

    DbgPrintEx(DPFLTR_DEFAULT_ID, DPFLTR_INFO_LEVEL, "pvmpower: loaded for the DroidVM PSCI power path\n");
    return STATUS_SUCCESS;
}

NTSTATUS
DriverEntry(_In_ PDRIVER_OBJECT DriverObject, _In_ PUNICODE_STRING RegistryPath)
{
    WDF_DRIVER_CONFIG config;

    WDF_DRIVER_CONFIG_INIT(&config, PvmPowerEvtDeviceAdd);
    return WdfDriverCreate(DriverObject, RegistryPath, WDF_NO_OBJECT_ATTRIBUTES, &config, WDF_NO_HANDLE);
}
